### ISSUE TITLE
Question about the implementation of binary modules

### ISSUE THREAD

**Issue by ThisisBillhe** [htqin/BiBERT#4]
Hi Haotong,
Thanks for your excellent work! However, I am curious why the weights have scaling_factors while the activations don't in modules like QuantizeLinear ( in modeling_quant.py). Previous work like IR-NET has the same implementation.
Also, none of the operands calculates the scaling factor for matrix multiplication in the Attention module (such as attn@value). Why? 

Looking forward to your reply!

**Comment by htqin** [comment]
Thanks for your attention! We consider calculating the scaling factor for activation will cause additional real-time computation, while the weight and its scaling factor are fixed during inference. For the matrix multiplication in the attention module, the two inputs should be seen as the activation since they are obtained in real-time during inference, thus we remove all scaling factors for this operation for inference efficiency. Some previous binarization works also consider the scaling factor of activation or make the scaling factor learnable to account for the effect of activation, such as XNOR-Net and XNOR++ (just for reference and comparison).
